--
-- PostgreSQL database dump
--

\restrict P2qe9DZLynG3IJXkhJlf35IdWIes7IsD2vzo8s9ZXLv4wbHvVfVAcf2J7BeKg3g

-- Dumped from database version 14.19
-- Dumped by pg_dump version 14.19

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accounts; Type: TABLE; Schema: public; Owner: devuser
--

CREATE TABLE public.accounts (
    account_id bigint NOT NULL,
    account_number bigint,
    balance integer,
    propietary_id bigint,
    state character varying(255),
    type character varying(255),
    CONSTRAINT accounts_state_check CHECK (((state)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[]))),
    CONSTRAINT accounts_type_check CHECK (((type)::text = ANY ((ARRAY['SAVINGS'::character varying, 'CHECKING'::character varying])::text[])))
);


ALTER TABLE public.accounts OWNER TO devuser;

--
-- Name: accounts_account_id_seq; Type: SEQUENCE; Schema: public; Owner: devuser
--

ALTER TABLE public.accounts ALTER COLUMN account_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: clients; Type: TABLE; Schema: public; Owner: devuser
--

CREATE TABLE public.clients (
    password character varying(255),
    state character varying(255),
    person_id bigint NOT NULL,
    CONSTRAINT clients_state_check CHECK (((state)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[])))
);


ALTER TABLE public.clients OWNER TO devuser;

--
-- Name: movements; Type: TABLE; Schema: public; Owner: devuser
--

CREATE TABLE public.movements (
    movement_id bigint NOT NULL,
    amount integer,
    balance integer,
    movement_date timestamp(6) without time zone,
    type character varying(255),
    account_id bigint,
    CONSTRAINT movements_type_check CHECK (((type)::text = ANY ((ARRAY['DEPOSIT'::character varying, 'WITHDRAWAL'::character varying])::text[])))
);


ALTER TABLE public.movements OWNER TO devuser;

--
-- Name: movements_movement_id_seq; Type: SEQUENCE; Schema: public; Owner: devuser
--

ALTER TABLE public.movements ALTER COLUMN movement_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.movements_movement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: people; Type: TABLE; Schema: public; Owner: devuser
--

CREATE TABLE public.people (
    person_id bigint NOT NULL,
    address character varying(255),
    age integer NOT NULL,
    gender character varying(255),
    identification character varying(255),
    name character varying(255),
    phone_number character varying(255),
    CONSTRAINT people_gender_check CHECK (((gender)::text = ANY ((ARRAY['MALE'::character varying, 'FEMALE'::character varying, 'OTHER'::character varying])::text[])))
);


ALTER TABLE public.people OWNER TO devuser;

--
-- Name: people_person_id_seq; Type: SEQUENCE; Schema: public; Owner: devuser
--

ALTER TABLE public.people ALTER COLUMN person_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.people_person_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: devuser
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_pkey PRIMARY KEY (account_id);


--
-- Name: clients clients_pkey; Type: CONSTRAINT; Schema: public; Owner: devuser
--

ALTER TABLE ONLY public.clients
    ADD CONSTRAINT clients_pkey PRIMARY KEY (person_id);


--
-- Name: movements movements_pkey; Type: CONSTRAINT; Schema: public; Owner: devuser
--

ALTER TABLE ONLY public.movements
    ADD CONSTRAINT movements_pkey PRIMARY KEY (movement_id);


--
-- Name: people people_pkey; Type: CONSTRAINT; Schema: public; Owner: devuser
--

ALTER TABLE ONLY public.people
    ADD CONSTRAINT people_pkey PRIMARY KEY (person_id);


--
-- Name: movements fk1a6nru7corjv5b2vidld4ef5r; Type: FK CONSTRAINT; Schema: public; Owner: devuser
--

ALTER TABLE ONLY public.movements
    ADD CONSTRAINT fk1a6nru7corjv5b2vidld4ef5r FOREIGN KEY (account_id) REFERENCES public.accounts(account_id);


--
-- Name: clients fk9q37okgu11okhncvbqinehbbb; Type: FK CONSTRAINT; Schema: public; Owner: devuser
--

ALTER TABLE ONLY public.clients
    ADD CONSTRAINT fk9q37okgu11okhncvbqinehbbb FOREIGN KEY (person_id) REFERENCES public.people(person_id);


--
-- PostgreSQL database dump complete
--

\unrestrict P2qe9DZLynG3IJXkhJlf35IdWIes7IsD2vzo8s9ZXLv4wbHvVfVAcf2J7BeKg3g

