spring:
  application:
    name: client-person-microservice
  datasource:
    username: postgres.cpnpasztdwperymygkiv
    password: 9yEjHQZib03acNTM
    url: jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
