server:
  port: 8080
spring:
  kafka:
    bootstrap-servers: 192.168.0.6:29092
  application:
    name: client-person-microservice
  datasource:
    username: devuser
    password: devpassword
    url: jdbc:postgresql://192.168.0.6:5432/devdb
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
