server:
  port: 8080
spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:192.168.0.6:29092}
  application:
    name: client-person-microservice
  datasource:
    username: ${DB_USERNAME:devuser}
    password: ${DB_PASSWORD:devpass}
    url: ${DB_URL:jdbc:postgresql://192.168.0.6:5432/devdb}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:update}
    database-platform: org.hibernate.dialect.PostgreSQLDialect

com:
  devsu:
    clients-service:
      url: ${CLIENT_SERVICE_URL:http://localhost:8080}