server:
  port: 8081
spring:
  kafka:
    bootstrap-servers: 192.168.0.6:29092
  application:
    name: client-person-microservice
  datasource:
    username: devuser
    password: devpassword
    url: jdbc:postgresql://192.168.0.6:5432/devdb
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

com:
  devsu:
    clients-service:
      url: http://localhost:8080